### PR TITLE
Simplify Using Existing Gtest Bazel Rule

### PR DESCRIPTION
**Pull request by hostilefork**
The sample apparently predates Google's Gtest having a BUILD.bazel rule.  There's a better way now:

https://stackoverflow.com/a/51847781

Adds some comments, a .bazelversion, and switches to use the recommended BUILD.bazel instead of just BUILD.  See details on individual commits.

### CODE REVIEW

**Comment by jhgorse** [comment]
Needed to
```
chmod +x
	modified:   clang_tidy/run_clang_tidy.sh
	modified:   make.sh
```

**Comment by jhgorse** [comment]
On macOS:
```
> ./make.sh
DEBUG: /private/var/tmp/_bazel_jhg/b509ad82de1a92767e3fc83c89b200f3/external/bazel_tools/tools/osx/xcode_configure.bzl:89:14: Invoking xcodebuild failed, developer dir: /Volumes/mOSXcs/Applications/Xcode.app/Contents/Developer ,return code 256, stderr: Timed out, stdout:
INFO: Analyzed target //main:hello-world (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //main:hello-world up-to-date:
  bazel-bin/main/hello-world
INFO: Elapsed time: 0.109s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
DEBUG: /private/var/tmp/_bazel_jhg/b509ad82de1a92767e3fc83c89b200f3/external/bazel_tools/tools/osx/xcode_configure.bzl:89:14: Invoking xcodebuild failed, developer dir: /Volumes/mOSXcs/Applications/Xcode.app/Contents/Developer ,return code 256, stderr: Timed out, stdout:
INFO: Analyzed target //main:hello-world (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /Users/jhg/Documents/work2016/bazel-playground/lib/BUILD.bazel:1:11: Run clang-tidy on lib/hello-time.cc failed: (Exit 127): clang_tidy failed: error executing command bazel-out/darwin-fastbuild/bin/clang_tidy/clang_tidy bazel-out/darwin-fastbuild/bin/lib/lib/hello-time.cc.clang-tidy.yaml --export-fixes ... (remaining 28 argument(s) skipped)
bazel-out/darwin-fastbuild/bin/clang_tidy/clang_tidy: line 14: clang-tidy: command not found
Aspect //clang_tidy:clang_tidy.bzl%clang_tidy_aspect of //main:hello-world failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.130s, Critical Path: 0.03s
INFO: 4 processes: 4 internal.
FAILED: Build did NOT complete successfully
Exit 1
```

**Comment by hostilefork** [comment]
`clang-tidy` does not appear to be one of the things you get on OS X with XCode :-/

I personally think that one is better off doing development inside a VirtualBox with Linux, to get the best tooling/instrumentation.  It also is nice to be able to snapshot VMs...roll them back, install more intrusive tools and take bigger risks than you might want to do on the host system.  (Feeling some deja-vu in saying this; but I do say it often.)  It's as easy to get things as `sudo apt install clang-tidy`.

Nevertheless, most development tools have a way to be installed on Mac OS, e.g. via brew.  It looks like it clang-tidy doesn't come as its own package, but you get it with LLVM:

https://gist.github.com/sleepdefic1t/e9bdb1a66b05aa043ab9a2ab6c929509

*(It turns out that the default build of clang/LLVM does not have an AVR backend either :-/ but this is not a deal-breaker necessarily for using clang-tidy on sources, as it doesn't matter what platform the code is being generated for to catch the semantic errors.  Investigating how well clang can work with the GCC AVR headers.)*

**Comment by jhgorse** [comment]
Even with the clang-tidy installed on macOS, it broke. Works fine on Windows WSL. Pulling.

**Comment by jhgorse** [comment]
Installed brew llvm and symlinked the clang-tidy. We get a bit further.

Pulled latest, permissions are still lack +x for macOS.

Output of make.sh on macOS:
```
⌁74% [jhg:~/Documents/work2016/bazel-playground] hostilefork/master 1 ± bash make.sh
...
INFO: Found 1 target...
ERROR: /Users/jhg/Documents/work2016/bazel-playground/main/BUILD.bazel:8:10: Run clang-tidy on main/hello-world.cc failed: (Exit 1): clang_tidy failed: error executing command bazel-out/darwin-fastbuild/bin/clang_tidy/clang_tidy bazel-out/darwin-fastbuild/bin/main/main/hello-world.cc.clang-tidy.yaml --export-fixes ... (remaining 32 argument(s) skipped)
src/main/tools/process-wrapper-legacy.cc:80: "execvp(bazel-out/darwin-fastbuild/bin/clang_tidy/clang_tidy, ...)": Permission denied
...
```
chmod +x clang_tidy

Then we get string.h cannot be found.

```
⌁74% [jhg:~/Documents/work2016/bazel-playground] hostilefork/master(+0/-0) ± bash make.sh
INFO: Analyzed target //main:hello-world (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //main:hello-world up-to-date:
  bazel-bin/main/hello-world
INFO: Elapsed time: 0.110s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Analyzed target //main:hello-world (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /Users/jhg/Documents/work2016/bazel-playground/main/BUILD.bazel:1:11: Run clang-tidy on main/hello-greet.cc failed: (Exit 1): clang_tidy failed: error executing command bazel-out/darwin-fastbuild/bin/clang_tidy/clang_tidy bazel-out/darwin-fastbuild/bin/main/main/hello-greet.cc.clang-tidy.yaml --export-fixes ... (remaining 28 argument(s) skipped)
11506 warnings and 1 error generated.
Error while processing /private/var/tmp/_bazel_jhg/b509ad82de1a92767e3fc83c89b200f3/execroot/__main__/main/hello-greet.cc.
Suppressed 11506 warnings (11506 in non-user code).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from system headers as well.
Found compiler error(s).
/usr/local/Cellar/llvm/11.1.0_1/bin/../include/c++/v1/string.h:60:15: error: 'string.h' file not found [clang-diagnostic-error]
#include_next <string.h>
              ^
Aspect //clang_tidy:clang_tidy.bzl%clang_tidy_aspect of //main:hello-world failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.337s, Critical Path: 1.23s
INFO: 4 processes: 4 internal.
FAILED: Build did NOT complete successfully
```

**Pull request merged**
